import { StyleSheet } from 'react-native';

const OnboardingStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
        paddingTop: 50,
        paddingHorizontal: 20,
    },
    scrollContent: {
        paddingBottom: 110,
    },
    logo: {
        width: 180,
        height: 120,
        alignSelf: 'center',
        marginBottom: 20,
    },
    title: {
        fontSize: 26,
        fontWeight: '700',
        color: '#008080',
        textAlign: 'center',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 16,
        fontWeight: '500',
        color: '#333',
        textAlign: 'center',
        marginBottom: 15,
    },
    description: {
        fontSize: 14,
        color: '#555',
        textAlign: 'center',
        marginBottom: 20,
        lineHeight: 20,
    },
    bulletTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#008080',
        marginVertical: 10,
        textAlign: 'left',
    },
    bulletRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    bullet: {
        fontSize: 14,
        color: '#333',
        marginLeft: 8,
        flexShrink: 1,
    },
    note: {
        fontSize: 12,
        color: '#888',
        textAlign: 'center',
        marginTop: 20,
        lineHeight: 18,
    },
    button: {
        backgroundColor: '#008080',
        paddingVertical: 15,
        paddingHorizontal: 25,
        borderRadius: 12,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 3,
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    bottomButtonContainer: {
        position: 'absolute',
        bottom: 30,
        left: 20,
        right: 20,
        alignItems: 'center',
        zIndex: 10,
    },
    iconContainer: {
        alignItems: 'center',
        marginVertical: 20,
    },
    offerCard: {
        backgroundColor: '#f8fdfd',
        padding: 15,
        borderRadius: 16,
        marginVertical: 15,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 3,
    },
    offerText: {
        fontSize: 14,
        color: '#008080',
        textAlign: 'center',
    },
    cardRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 15,
        backgroundColor: '#f8fdfd',
        borderRadius: 12,
        marginVertical: 6,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 1 },
        shadowRadius: 3,
        elevation: 2,
    },
    cardText: {
        marginLeft: 12,
        fontSize: 14,
        color: '#333',
        flexShrink: 1,
    },
});

export default OnboardingStyles;
